
config:
  secretKey: 'K09E635266556A58X2X272357538782F413F44DAS472B4B6250645367566B5970'

#server:
#  port: 9000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://192.168.1.5:5432/omnierpdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  application:
    name: BE-OMNIERP-API
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

