
config:
  secretKey: '404E635266556A58X2X272357538782F413F4428472B4B6250645367566B5970'

server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/omnierpdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  application:
    name: BE-OMNIERP-API
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
